# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: episode-sim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='episode-sim.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65pisode-sim.proto\"(\n\x0b\x45pisodeSims\x12\x19\n\x04rows\x18\x01 \x03(\x0b\x32\x0b.EpisodeSim\"\x18\n\x03IDs\x12\x11\n\x04rows\x18\x01 \x03(\x0b\x32\x03.ID\"\x1f\n\x02ID\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05idNum\x18\x02 \x02(\r\"@\n\nEpisodeSim\x12\x0e\n\x06idNum1\x18\x01 \x02(\r\x12\x0e\n\x06idNum2\x18\x02 \x02(\r\x12\x12\n\nsimilarity\x18\x03 \x02(\x02'
)




_EPISODESIMS = _descriptor.Descriptor(
  name='EpisodeSims',
  full_name='EpisodeSims',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='EpisodeSims.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=61,
)


_IDS = _descriptor.Descriptor(
  name='IDs',
  full_name='IDs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='IDs.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=87,
)


_ID = _descriptor.Descriptor(
  name='ID',
  full_name='ID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ID.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idNum', full_name='ID.idNum', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=120,
)


_EPISODESIM = _descriptor.Descriptor(
  name='EpisodeSim',
  full_name='EpisodeSim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idNum1', full_name='EpisodeSim.idNum1', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idNum2', full_name='EpisodeSim.idNum2', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='similarity', full_name='EpisodeSim.similarity', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=186,
)

_EPISODESIMS.fields_by_name['rows'].message_type = _EPISODESIM
_IDS.fields_by_name['rows'].message_type = _ID
DESCRIPTOR.message_types_by_name['EpisodeSims'] = _EPISODESIMS
DESCRIPTOR.message_types_by_name['IDs'] = _IDS
DESCRIPTOR.message_types_by_name['ID'] = _ID
DESCRIPTOR.message_types_by_name['EpisodeSim'] = _EPISODESIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EpisodeSims = _reflection.GeneratedProtocolMessageType('EpisodeSims', (_message.Message,), {
  'DESCRIPTOR' : _EPISODESIMS,
  '__module__' : 'episode_sim_pb2'
  # @@protoc_insertion_point(class_scope:EpisodeSims)
  })
_sym_db.RegisterMessage(EpisodeSims)

IDs = _reflection.GeneratedProtocolMessageType('IDs', (_message.Message,), {
  'DESCRIPTOR' : _IDS,
  '__module__' : 'episode_sim_pb2'
  # @@protoc_insertion_point(class_scope:IDs)
  })
_sym_db.RegisterMessage(IDs)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'episode_sim_pb2'
  # @@protoc_insertion_point(class_scope:ID)
  })
_sym_db.RegisterMessage(ID)

EpisodeSim = _reflection.GeneratedProtocolMessageType('EpisodeSim', (_message.Message,), {
  'DESCRIPTOR' : _EPISODESIM,
  '__module__' : 'episode_sim_pb2'
  # @@protoc_insertion_point(class_scope:EpisodeSim)
  })
_sym_db.RegisterMessage(EpisodeSim)


# @@protoc_insertion_point(module_scope)
