# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: screen-time-timeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='screen-time-timeline.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ascreen-time-timeline.proto\")\n\tTimelines\x12\x1c\n\ttimelines\x18\x01 \x03(\x0b\x32\t.Timeline\"B\n\x08Timeline\x12\n\n\x02id\x18\x01 \x02(\t\x12\x1a\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x08.Cluster\x12\x0e\n\x06\x66rames\x18\x03 \x02(\x04\"5\n\x07\x43luster\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1e\n\ntimestamps\x18\x02 \x03(\x0b\x32\n.Timestamp\"\'\n\tTimestamp\x12\r\n\x05start\x18\x01 \x02(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x02(\x02'
)




_TIMELINES = _descriptor.Descriptor(
  name='Timelines',
  full_name='Timelines',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timelines', full_name='Timelines.timelines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=71,
)


_TIMELINE = _descriptor.Descriptor(
  name='Timeline',
  full_name='Timeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Timeline.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clusters', full_name='Timeline.clusters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frames', full_name='Timeline.frames', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=139,
)


_CLUSTER = _descriptor.Descriptor(
  name='Cluster',
  full_name='Cluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Cluster.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='Cluster.timestamps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=194,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Timestamp.start', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='Timestamp.end', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=235,
)

_TIMELINES.fields_by_name['timelines'].message_type = _TIMELINE
_TIMELINE.fields_by_name['clusters'].message_type = _CLUSTER
_CLUSTER.fields_by_name['timestamps'].message_type = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Timelines'] = _TIMELINES
DESCRIPTOR.message_types_by_name['Timeline'] = _TIMELINE
DESCRIPTOR.message_types_by_name['Cluster'] = _CLUSTER
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timelines = _reflection.GeneratedProtocolMessageType('Timelines', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINES,
  '__module__' : 'screen_time_timeline_pb2'
  # @@protoc_insertion_point(class_scope:Timelines)
  })
_sym_db.RegisterMessage(Timelines)

Timeline = _reflection.GeneratedProtocolMessageType('Timeline', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINE,
  '__module__' : 'screen_time_timeline_pb2'
  # @@protoc_insertion_point(class_scope:Timeline)
  })
_sym_db.RegisterMessage(Timeline)

Cluster = _reflection.GeneratedProtocolMessageType('Cluster', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTER,
  '__module__' : 'screen_time_timeline_pb2'
  # @@protoc_insertion_point(class_scope:Cluster)
  })
_sym_db.RegisterMessage(Cluster)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'screen_time_timeline_pb2'
  # @@protoc_insertion_point(class_scope:Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)


# @@protoc_insertion_point(module_scope)
